version: '3'
services:
  keystone-mongodb:
    image: mongo:latest
    ports: 
      - 27017:27017
    hostname: localhost
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
 
volumes:
  db-data:
  mongo-config: